git:
  depth: 3

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - CC=gcc-4.7 CXX=g++-4.7

addons:
  apt:
    packages:
      - gcc-4.7
      - g++-4.7
    sources:
      - ubuntu-toolchain-r-test

install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt
  - curl -L https://github.com/utwente-fmt/sylvan/tarball/v1.0.0 -o sylvan.tar.gz
  - echo '9877fe07a8cfe9889152e29624a4c5b283cb34672ec524ccb3edb313b3057fbf8ef45622a49796fae17aa24e0baea5ccfa18f1bc5923e3c55245ab3e3c1927c8  sylvan.tar.gz' | shasum -a 512 -c -
  - mkdir sylvan
  - tar xzf sylvan.tar.gz -C sylvan --strip=1
  - cd sylvan
  - autoreconf -fi
  - ./configure
  - make
  - export LD_LIBRARY_PATH=`pwd`/src/.libs:$LD_LIBRARY_PATH
  - cd ..
  # dd
  - python setup.py install --fetch --cudd --sylvan

script:
  - cd tests/
  - nosetests --with-coverage --cover-package=dd

after_success:
  - coveralls
